version: 2
jobs:
  build_sandbox:
      docker:
        - image: circleci/node:8.10
      filters:
            branches:
              ignore: /^master*/
      steps:
        - checkout

        - run:
            name: Install dependencies
            command: npm install
        - run:
            name: Deploy application
            command: |
              if [ "${CIRCLE_BRANCH}" == "circleci-stack" ]; then
                npm run deploy-sandbox
              fi

  build_dev:
      docker:
        - image: circleci/node:8.10
      filters:
        branches:
          only: master
      steps:
        - checkout

        - run:
            name: Install dependencies
            command: npm install
        - run:
            name: Deploy application
            command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                npm run deploy-dev
              fi

  test:
    docker:
      - image: circleci/node:8.10
    steps:
        - run:
            name: Run unit tests
            command: npm test

workflows:
  version: 2
  build_sandbox:
    jobs:
      - build_sandbox
      - test
  build_dev:
    jobs:
      - build_dev
      - test
