version: 2
jobs:
  build:
      docker:
        - image: circleci/node:8.10
      steps:
        - checkout

        - run:
            name: Install dependencies
            command: npm install
        - run:
            name: Deploy application
            command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                npm run deploy-dev
              else
                npm run deploy-sandbox
              fi

  test:
    docker:
      - image: circleci/node:8.10
    steps:
        - run:
            name: Run unit tests
            command: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
