version: 2
jobs:
  build:
      working_directory: ~/SmartPath-POC/demo-service
      filters:
        branches:
          only: master
      steps:
        - checkout

        - restore_cache:
            keys:
              - dependencies-cache-{{ checksum "package.json" }}
              # fallback to using the latest cache if no exact match is found
              - dependencies-cache

        - run:
            name: Install Serverless CLI and dependencies
            command: |
              sudo npm i -g serverless
              npm install

        - run:
            name: Deploy application
            command: sls deploy

        - save_cache:
            paths:
              - node_modules
            key: dependencies-cache-{{ checksum "package.json" }}
