version: 2
jobs:
  build:
      docker:
        - image: circleci/node:8.10
      working_directory: ~/SmartPath-POC/demo-service
      filters:
        branches:
          only: master
      steps:
        - checkout

        - run:
            name: Install Serverless CLI and dependencies
            command: |
              npm install

        - run:
            name: Deploy application
            command: npm run deploy
