version: 2
jobs:
  build:
      docker:
        - image: circleci/node:8.10
      steps:
        - checkout

        - run:
            name: Install dependencies
            command: npm install

  deploy_sandbox:
      steps:
        - run:
            name: Deploy application
            command: npm run deploy-sandbox

  test:
    docker:
      - image: circleci/node:8.10
    filters:
      branches:
        only: master
    steps:
        - run:
            name: Run unit tests
            command: npm test

workflows:
  version: 2
  build_sandbox:
    jobs:
      - build
      - deploy_sandbox
      - test
