service:
  name: aws-nodejs-typescript

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  environment: 
    FTP_USER: ${ssm:FTP_USER}
    FTP_PW: ${ssm:FTP_PW}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
  download:
    handler: ftpDownload/index.download
    events:
      - http:
          method: get
          path: ftpDownload
